### ISSUE TITLE
Hi Sorry to bother you

### ISSUE THREAD

**Issue by Zelly9191** [jiangzhengwenjz/csm3#13]
I was just made aware that this project is a thing. I'm a team leader of the English translation project for this game. I would love to reach out and chat with either of you whenever you have the chance. If you have a discord feel free to send a message to zelly_9191 or If you have a different preferred method of contact, let me know. I'm sure we can work something out. I would love to be able to discuss things or perhaps share our knowledge between each other.

**Comment by jiangzhengwenjz** [comment]
I've sent a friend request on Discord.
